@include('templates.formulario.input', ['input' => 'cpf', 'attributes' => ['placeholder' => 'CPF']])
@include('templates.formulario.input', ['input' => 'name', 'attributes' => ['placeholder' => 'Nome Completo']])
@include('templates.formulario.input', ['input' => 'phone', 'attributes' => ['placeholder' => 'Telefone']])
@include('templates.formulario.input', ['input' => 'email', 'attributes' => ['placeholder' => 'E-mail']])
@include('templates.formulario.password', ['input' => 'password', 'attributes' => ['placeholder' => 'Senha']])
